### ISSUE TITLE
 Ingress.networking.k8s.io "vaultwarden-release" is invalid:

### ISSUE THREAD

**Issue by outbackdingo** [guerzon/vaultwarden#125]
Error: INSTALLATION FAILED: 1 error occurred:
	* Ingress.networking.k8s.io "vaultwarden-release" is invalid: [spec.rules[0].host: Invalid value: "https://warden.domain.com": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.tls[0].hosts[0]: Invalid value: "https://warden.domain.com": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]

**Comment by guerzon** [comment]
Can you paste your values yaml?

**Comment by ARyaskov** [comment]
Hello, @guerzon! First of all I wanna thank you for creating such a good project!
I faced the same issue.
Steps to reproduce:
1) `helm repo add vaultwarden https://guerzon.github.io/vaultwarden`

2) `export VAULTWARDEN_DOMAIN_NAME=https://pass.mydomain.com`

3) `helm install vaultwarden-release vaultwarden/vaultwarden --set "ingress.enabled=true" --set "ingress.hostname=$VAULTWARDEN_DOMAIN_NAME"`
4) Got ```Error: INSTALLATION FAILED: 1 error occurred:
	* Ingress.networking.k8s.io "vaultwarden-release" is invalid: [spec.rules[0].host: Invalid value: "https://pass.mydomain.com": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.tls[0].hosts[0]: Invalid value: "https://pass.mydomain.com": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]```
	
In case I just specify it without `https://` prefix `export VAULTWARDEN_DOMAIN_NAME=pass.mydomain.com` Vaultwarden goes to CrashloopBackOff with `Error validating domain: relative URL without a base   | Error loading config: DOMAIN variable needs to contain the protocol (http, https). Use 'http[s]://bw.example.com' instead of 'bw.example.com'`

**Comment by guerzon** [comment]
Hi @outbackdingo, @ARyaskov,

The `domain` Helm value/the `DOMAIN` environment variable should contain the scheme, ex.: `"https://vaultwarden.contoso.com"`.

On the other hand, `ingress.hostname` should only contain the host part (i.e. without the scheme), ex.: `vaultwarden.contoso.com`.
