### ISSUE TITLE
Latest update to chart V0.17.0 breaks upgrade process

### ISSUE THREAD

**Issue by groundhog2k** [guerzon/vaultwarden#58]
When trying to upgrade an existing vaultwarden deployment based on chart version 0.16.1 to chart 0.17.0 the helm deployment fails with: 

Error: UPGRADE FAILED: cannot patch "vault-vaultwarden" with kind StatefulSet: StatefulSet.apps "vault-vaultwarden" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden

I guess this is related to changes made in the volumeMounts: section.

**Comment by Supporterino** [comment]
Phasing the same problem when upgrading the helm chart from version `0.17.0` to `0.18.0`. With the help of argo-cd I could track the error further down. Since the `Statefulset` is responsible for handling the `PersistentVolumeClaim` the `persistentVolumeClaimRetentionPolicy` key is added to the `Statefulset` in the helm templates. But k8s doesn't allow the adjustment of this field. At the moment I haven't found a workaround yet. Only option I see is recreating the `Statefulset` which could lead to a loss of the `PersistentVolumeClaim`
![Screenshot 2023-12-15 at 20 50 24](https://github.com/guerzon/vaultwarden/assets/25184990/575bd7b5-f53e-4219-a5f2-31289b34d575)
